services:
  #Database
  springcreek_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3327:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: springcreek_db
  #Web
  springcreek_wp:
    depends_on:
      - springcreek_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8090:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: springcreek_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: springcreek_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  springcreek_myadmin:
    image: phpmyadmin:latest
    container_name: springcreek_myadmin
    restart: "no"
    ports:
      - 5010:80
    environment:
      PMA_HOST: springcreek_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - springcreek_db
volumes:
  db_data:
  wp-content:
